server:
  port: 80
  servlet:
    context-path: /ppsd

spring:
  datasource:
#    username: root
#    password: networklab
#    url: jdbc:mysql://localhost:3306/geas?serverTimezone=UTC
    username: djw
    password: xhyc19951008
    url: jdbc:mysql://210.45.176.93:3306/bioinfo?serverTimezone=UTC

    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 30000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  thymeleaf:
    cache: false
  mvc:
    date-format: yyyy-MM-dd
    hiddenmethod:
      filter:
        enabled: true
  cache:
    type: caffeine



logging:
  config: classpath:log4j2.xml
  level.com.julio: trace
#  level.com.julio: info


pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
  helper-dialect: mysql
management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /monitor
      cors:
        #allowed-origins: http://localhost:10888
        allowed-origins: http://ne.ahau.edu.cn/
        allowed-methods: GET,POST
        allowed-headers: '*'
        allow-credentials: true
  server:
    address: localhost
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true